refactor: add `-p` option

diff --git a/http-zsh b/http-zsh
--- a/http-zsh
+++ b/http-zsh
@@ -7,15 +7,33 @@
 
 zparseopts -D -E -F - \
     s=serv_type -static=serv_type \
-    h=serv_type -html=serv_type -port:=port_value || exit 1
+    h=serv_type -html=serv_type \
+    p:=port_value -port:=port_value || exit 1
+
+port_value_error="Error - pass one port option:\n\t(-p|--port)"
+
+if [[ "${#port_value}" -ne "2" && "${#port_value}" -gt "1" ]]; then
+    echo "$port_value_error" && exit
+fi
+
+
+case "${port_value:0:1}" in
+-p | --port)
+    readonly PORT="${port_value:1:1}"
+    ;;
+*)
+    readonly PORT=1234
+    ;;
+esac
 
 server_type_error="Error - pass one server type option:\n\tstatic (-s|--static)\n\thtml (-h|--html)"
+
 if [[ "${#serv_type}" != 1 ]]; then
     echo "$server_type_error" && exit
 fi
+
 serv_type=${serv_type:0:1}
 
-readonly PORT="$([ ${#port_value} = 2 ] && echo ${port_value:1:1} || echo 6969)"
 readonly BR="\r\n"
 readonly RESPONSE_FIFO='response_fifo'
 readonly DEFAULT_BODY="<h1>Hello, world!</h1>"
